#!/usr/bin/env bash
# Displays the time for 12 horus and 59 minutes.
#   Displays hours from 0 to 12
#   Displays minutes from 1 to 59

hour=0

while ((hour < 13))
do
	minute=0
	echo "Hour: $hour"

	while ((minute < 59))
	do
		((minute++))
		echo $minute
	done
	
	((hour++))
done
